import { Button } from "@mui/material";
import Head from "next/head";
import Image from "next/image";
import CountdownBar from "../components/CountdownBar";
import { useAppContext } from "../controllers/AppWrapper";
import styles from "../styles/Home.module.css";

function Home() {
  const appContext = useAppContext();
  const { gameHandler } = appContext;

  return (
    <>
      <Head>
        <title>Robban&apos;s Pointless quiz</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <div style={{ display: "flex" }}>
          <div>
            <h2 style={{ marginBottom: 50 }}>Robban&apos;s Pointless Quiz</h2>
            <Image
              src="/images/logo.png"
              alt="Logo"
              width={384}
              height={214}
              style={{ marginBottom: 50 }}
            />
            <div className={styles.menu}>
              <Button
                className={styles.menuButton}
                variant="contained"
                onClick={() => gameHandler.requestNewGame()}
                fullWidth
              >
                New game
              </Button>
              <Button
                className={styles.menuButton}
                variant="contained"
                onClick={() => gameHandler.requestToBeHost()}
                fullWidth
              >
                Host
              </Button>
            </div>
          </div>
          <CountdownBar
            to={0}
            callback={() => {
              console.log("*** callback");
            }}
          />
        </div>
      </main>
    </>
  );
}

export default Home;
